package com.my.testgen.dao.mybatis.vo;


public class UserLoginInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_login_info.uid
     *
     * @mbg.generated
     */
    private Long uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_login_info.account
     *
     * @mbg.generated
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_login_info.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_login_info.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_login_info.udid
     *
     * @mbg.generated
     */
    private String udid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_login_info.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_login_info.channel
     *
     * @mbg.generated
     */
    private String channel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_login_info.channel_uid
     *
     * @mbg.generated
     */
    private String channelUid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_login_info.uid
     *
     * @return the value of u_login_info.uid
     *
     * @mbg.generated
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_login_info.uid
     *
     * @param uid the value for u_login_info.uid
     *
     * @mbg.generated
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_login_info.account
     *
     * @return the value of u_login_info.account
     *
     * @mbg.generated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_login_info.account
     *
     * @param account the value for u_login_info.account
     *
     * @mbg.generated
     */
    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_login_info.email
     *
     * @return the value of u_login_info.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_login_info.email
     *
     * @param email the value for u_login_info.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_login_info.phone
     *
     * @return the value of u_login_info.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_login_info.phone
     *
     * @param phone the value for u_login_info.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_login_info.udid
     *
     * @return the value of u_login_info.udid
     *
     * @mbg.generated
     */
    public String getUdid() {
        return udid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_login_info.udid
     *
     * @param udid the value for u_login_info.udid
     *
     * @mbg.generated
     */
    public void setUdid(String udid) {
        this.udid = udid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_login_info.password
     *
     * @return the value of u_login_info.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_login_info.password
     *
     * @param password the value for u_login_info.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_login_info.channel
     *
     * @return the value of u_login_info.channel
     *
     * @mbg.generated
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_login_info.channel
     *
     * @param channel the value for u_login_info.channel
     *
     * @mbg.generated
     */
    public void setChannel(String channel) {
        this.channel = channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_login_info.channel_uid
     *
     * @return the value of u_login_info.channel_uid
     *
     * @mbg.generated
     */
    public String getChannelUid() {
        return channelUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_login_info.channel_uid
     *
     * @param channelUid the value for u_login_info.channel_uid
     *
     * @mbg.generated
     */
    public void setChannelUid(String channelUid) {
        this.channelUid = channelUid;
    }


	       ////*******自定义开始********/
        //***********自定义结束****////
}
